Kndp 36 stack operator
web-seven/kndp pull request #36
Opened 2023-07-31 13:53 UTC by Timex1854

2023-07-31 15:14 UTC, web7evgheni requested changes

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +		http.HandleFunc("/api/objects", func(w http.ResponseWriter, r *http.Request) {
@Timex1854 Why not "/api/stacks" ?

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +					filePath := filepath.Join("./.platform/stacks", fileName)
@Timex1854 Please use environment variables for paths

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +				}
@Timex1854 Replace with:
`err = applyManifest(content, reqBody.Activate)`

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +			if err := http.ListenAndServe(":8080", corsWrappedHandler); err != nil {
@Timex1854 Please use environment variables for port

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +	func getFilesInDirectory(dirPath, suffix string) []string {
@Timex1854 Main function always shall be last one.

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +
@Timex1854 No Spaces

2023-07-31 15:14 UTC, web7evgheni commented on packages/operator/main.go
> +func applyManifest(content []byte, delete bool) error {
@Timex1854 please add doc comments to all functions

2023-08-08 19:00 UTC, art10m commented on packages/stack/stack-operator/Dockerfile
> +COPY --from=build /operator /
@Timex1854 Use this approch for installing kubectl 
```suggestion
COPY --from=build /operator /
COPY --from=alpine/k8s:1.24.16 /usr/bin/kubectl /usr/local/bin/kubectl
```

2023-08-08 19:00 UTC, art10m commented on packages/stack/stack-operator/Dockerfile
> +WORKDIR /app
```suggestion
WORKDIR /app
ENV STACKS_DIRECTORY=""
```

2023-08-08 19:00 UTC, art10m commented on packages/stack/stack-operator/main.go
> +	if port == "" {
@Timex1854 Pls use ternary operator for cleaner code

2023-08-09 07:31 UTC, Timex1854 commented on packages/stack/stack-operator/main.go
> +	if port == "" {
ternary operator is absent in golang

2023-08-09 12:06 UTC, web7evgheni requested changes

2023-08-09 12:06 UTC, web7evgheni commented on packages/kndp/charts/kndp/Chart.yaml
> +    repository: https://kndp.io
@Timex1854 In this PR you working with stack operator, why you add cluster operator? Please remove it, it shall be added by other PR where you change cluster operator.

2023-08-09 16:05 UTC, merged