Feature/KNDP-42: Applied same theme as Docusaurus.io with empty Intro,empty home page, header and items
web-seven/kndp pull request #40
Opened 2023-08-02 08:26 UTC by Enotmd

![image](https://github.com/web-seven/kndp/assets/109219657/d31b776a-e451-4f28-a2bd-689d4460d49a)
![image](https://github.com/web-seven/kndp/assets/109219657/5a382768-b91e-438a-a68b-b2bbc99e4027)
"screenshots from local testing"

Project website theme and basic pages:
-Applied to website same theme as Docusaurus.io.
-Empty home page with header and items on it like requested
-Created Docs section with temporarily empty Introduction and  Installation on Linux Platform.

2023-08-03 12:19 UTC, art10m commented on website/docs/getting started/install/linux.md
@Enotmd do not use naming of folder with spaces

2023-08-03 12:23 UTC, art10m commented on website/sidebars.js
> +    // highlight-start
@Enotmd Remove unnecessary comments

2023-08-03 12:23 UTC, art10m commented on website/sidebars.js
> +      dirName: '.', // '.' means the current docs folder
@Enotmd Remove unnecessary comments

2023-08-03 12:23 UTC, art10m commented on website/sidebars.js
> +    // highlight-end
@Enotmd Remove unnecessary comment

2023-08-03 14:49 UTC, art10m requested changes

2023-08-03 14:49 UTC, art10m commented on website/sidebars.js
> +      dirName: '.', // '.' means the current docs folder
@Enotmd You forgot one comment

2023-08-09 11:50 UTC, web7evgheni approved these changes

2023-08-09 11:51 UTC, merged