feature/KNDP-46:  Merged the "build.yaml" workflow into the "releases.yaml" workflow as 2 jobs in a single workflow
web-seven/kndp pull request #41
Opened 2023-08-02 12:56 UTC by Enotmd

2023-08-02 13:24 UTC, art10m requested changes

2023-08-02 13:24 UTC, art10m commented on .github/workflows/releases.yaml
> +              cat build.txt | xargs -I {} dirname {} | awk -F'/' 'NF >= 2 { print $1 "/" $2 }' | uniq | xargs -I{} find {} -type f -name "Dockerfile" | xargs -I{} bash -c 'context=$(dirname "{}"); di
@Enotmd Please integrate this functionality into the deploy job instead of keeping it as a separate one.

2023-08-02 13:55 UTC, art10m commented on .github/workflows/releases.yaml
> +          password: ${{ secrets.ACCESS_TOKEN }}
@Enotmd The step should be relocated to the top, where all the job configurations are performed.

2023-08-02 13:56 UTC, art10m requested changes

2023-08-02 13:56 UTC, art10m commented on .github/workflows/releases.yaml
> +              cat build.txt | xargs -I {} dirname {} | awk -F'/' 'NF >= 2 { print $1 "/" $2 }' | uniq | xargs -I{} find {} -type f -name "Dockerfile" | xargs -I{} bash -c 'context=$(dirname "{}"); di
@Enotmd Integrate this step above "Build website" step

2023-08-02 14:43 UTC, Enotmd commented
So, if you open the workflow from the action tab, its clearly building and pushing (on branch knpd46 at the moment), but it doesnt go to github packages. 
@art10m 
![image](https://github.com/web-seven/kndp/assets/109219657/f7516168-3c4f-408a-ba1d-e892d87dd16d)

2023-08-03 09:49 UTC, art10m commented on .github/workflows/releases.yaml
> +
@Enotmd remove this line

2023-08-03 09:49 UTC, art10m commented on .github/workflows/releases.yaml
> +          CR_SKIP_EXISTING: true
@Enotmd Why did you switch it to true?

2023-08-03 10:29 UTC, Enotmd commented on .github/workflows/releases.yaml
> +          CR_SKIP_EXISTING: true
at one moment it didnt want to build cause it already existed and it failed the job, it was a problem of  docker registry login not in the right place. switched back

2023-08-03 12:01 UTC, art10m approved these changes

2023-08-03 12:02 UTC, merged