Bugfix/kndp 45 merge new created index with gh pages index
web-seven/kndp pull request #49
Opened 2023-08-15 08:21 UTC by Timex1854

possible failure of building kndp Dockerfile,  it needs some files that exists only in other pr, also i resolved empty index.yaml issue and everytime workflow will not have charts or Dockerfiles to release, it will keep the last version of index.yaml from gh-pages

2023-08-15 08:24 UTC, web7evgheni commented
@Timex1854 Please exclude changes which is not related to KNDP-45

2023-08-15 08:25 UTC, web7evgheni requested changes
Please exclude changes which is not related to KNDP-45

2023-08-16 12:48 UTC, web7evgheni requested changes

2023-08-16 13:03 UTC, Timex1854 commented on .github/workflows/releases.yaml
> +        if: ${{ failure() }}
i made the changes

2023-08-16 13:58 UTC, web7evgheni approved these changes

2023-08-16 13:58 UTC, merged